-- MySQL Script generated by MySQL Workbench
-- Thu Jan 14 11:14:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema disneydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `disneydb` ;

-- -----------------------------------------------------
-- Schema disneydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `disneydb` DEFAULT CHARACTER SET utf8 ;
USE `disneydb` ;

-- -----------------------------------------------------
-- Table `disneydb`.`parola_chiave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`parola_chiave` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`parola_chiave` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `testo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`avatar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`avatar` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`avatar` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `immagine` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`utente` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`utente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `cognome` VARCHAR(30) NOT NULL,
  `data_nascita` DATE NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `paese` VARCHAR(30) NOT NULL,
  `regione` VARCHAR(30) NOT NULL,
  `indirizzo` VARCHAR(50) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `avatar_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_utente_avatar1_idx` (`avatar_id` ASC) VISIBLE,
  CONSTRAINT `fk_utente_avatar1`
    FOREIGN KEY (`avatar_id`)
    REFERENCES `disneydb`.`avatar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`recensione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`recensione` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`recensione` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `voto` DECIMAL(2,1) NOT NULL,
  `titolo` VARCHAR(30) NOT NULL,
  `testo` MEDIUMTEXT NOT NULL,
  `data` DATE NOT NULL,
  `utente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recensione_utente1_idx` (`utente_id` ASC) VISIBLE,
  CONSTRAINT `fk_recensione_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `disneydb`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`regia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`regia` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`regia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `cognome` VARCHAR(30) NOT NULL,
  `anno_nascita` DATE NOT NULL,
  `eta` INT UNSIGNED NOT NULL,
  `nazionalità` VARCHAR(30) NOT NULL,
  `paese_nascita` VARCHAR(30) NOT NULL,
  `biografia` MEDIUMTEXT NOT NULL,
  `foto` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`personaggio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`personaggio` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`personaggio` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descrizione` MEDIUMTEXT NOT NULL,
  `data_nascita` DATE NOT NULL,
  `foto` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`notizia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`notizia` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`notizia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titolo` VARCHAR(30) NOT NULL,
  `fonte` VARCHAR(30) NOT NULL,
  `data_pubblicazione` DATE NOT NULL,
  `descrizione` MEDIUMTEXT NOT NULL,
  `categoria` VARCHAR(30) NOT NULL,
  `immagine` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`commento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`commento` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`commento` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `testo` MEDIUMTEXT NOT NULL,
  `data` DATE NOT NULL,
  `utente_id` INT UNSIGNED,
  `notizia_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commento_utente1_idx` (`utente_id` ASC) VISIBLE,
  INDEX `fk_commento_notizia1_idx` (`notizia_id` ASC) VISIBLE,
  CONSTRAINT `fk_commento_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `disneydb`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commento_notizia1`
    FOREIGN KEY (`notizia_id`)
    REFERENCES `disneydb`.`notizia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`ordine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`ordine` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`ordine` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `totale_parziale` DOUBLE(5,2) NOT NULL,
  `spese_spedizione` DOUBLE(5,2) NOT NULL,
  `utente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ordine_utente1_idx` (`utente_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordine_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `disneydb`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`indirizzo_spedizione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`indirizzo_spedizione` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`indirizzo_spedizione` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `cognome` VARCHAR(30) NOT NULL,
  `indirizzo1` VARCHAR(50) NOT NULL,
  `indirizzo2` VARCHAR(50) NULL,
  `paese` VARCHAR(30) NOT NULL,
  `regione` VARCHAR(30) NULL,
  `citta` VARCHAR(30) NOT NULL,
  `cap` CHAR(5) NOT NULL,
  `telefono` INT UNSIGNED NOT NULL,
  `utente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_indirizzo_spedizione_utente1_idx` (`utente_id` ASC) VISIBLE,
  CONSTRAINT `fk_indirizzo_spedizione_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `disneydb`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`metodo_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`metodo_pagamento` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`metodo_pagamento` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_carta` REAL UNSIGNED NOT NULL,
  `cvv` INT UNSIGNED NOT NULL,
  `data_scadenza` DATE NOT NULL,
  `nome_sulla_carta` VARCHAR(80) NOT NULL,
  `utente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_metodo_pagamento_utente1_idx` (`utente_id` ASC) VISIBLE,
  CONSTRAINT `fk_metodo_pagamento_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `disneydb`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`gruppo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`gruppo` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`gruppo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipologia utente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`gruppo_utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`gruppo_utente` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`gruppo_utente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `utente_id` INT UNSIGNED NOT NULL,
  `gruppo_id` INT UNSIGNED NOT NULL,
  INDEX `fk_utente_has_gruppo_gruppo1_idx` (`gruppo_id` ASC) VISIBLE,
  INDEX `fk_utente_has_gruppo_utente_idx` (`utente_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_utente_has_gruppo_utente`
    FOREIGN KEY (`utente_id`)
    REFERENCES `disneydb`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utente_has_gruppo_gruppo1`
    FOREIGN KEY (`gruppo_id`)
    REFERENCES `disneydb`.`gruppo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`servizi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`servizi` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`servizi` (
  `username` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`servizi_gruppo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`servizi_gruppo` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`servizi_gruppo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gruppo_id` INT UNSIGNED NOT NULL,
  `servizi_username` VARCHAR(50) NOT NULL,
  INDEX `fk_gruppo_has_servizi_servizi1_idx` (`servizi_username` ASC) VISIBLE,
  INDEX `fk_gruppo_has_servizi_gruppo1_idx` (`gruppo_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gruppo_has_servizi_gruppo1`
    FOREIGN KEY (`gruppo_id`)
    REFERENCES `disneydb`.`gruppo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gruppo_has_servizi_servizi1`
    FOREIGN KEY (`servizi_username`)
    REFERENCES `disneydb`.`servizi` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`parola_chiave_personaggio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`parola_chiave_personaggio` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`parola_chiave_personaggio` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `personaggio_id` INT UNSIGNED NOT NULL,
  `parola_chiave_id` INT UNSIGNED NOT NULL,
  INDEX `fk_personaggio_has_parola_chiave_parola_chiave1_idx` (`parola_chiave_id` ASC) VISIBLE,
  INDEX `fk_personaggio_has_parola_chiave_personaggio1_idx` (`personaggio_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_personaggio_has_parola_chiave_personaggio1`
    FOREIGN KEY (`personaggio_id`)
    REFERENCES `disneydb`.`personaggio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personaggio_has_parola_chiave_parola_chiave1`
    FOREIGN KEY (`parola_chiave_id`)
    REFERENCES `disneydb`.`parola_chiave` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`parola_chiave_notizia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`parola_chiave_notizia` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`parola_chiave_notizia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parola_chiave_id` INT UNSIGNED NOT NULL,
  `notizia_id` INT UNSIGNED NOT NULL,
  INDEX `fk_parola_chiave_has_notizia_notizia1_idx` (`notizia_id` ASC) VISIBLE,
  INDEX `fk_parola_chiave_has_notizia_parola_chiave1_idx` (`parola_chiave_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_parola_chiave_has_notizia_parola_chiave1`
    FOREIGN KEY (`parola_chiave_id`)
    REFERENCES `disneydb`.`parola_chiave` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parola_chiave_has_notizia_notizia1`
    FOREIGN KEY (`notizia_id`)
    REFERENCES `disneydb`.`notizia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`parola_chiave_regia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`parola_chiave_regia` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`parola_chiave_regia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `regia_id` INT UNSIGNED NOT NULL,
  `parola_chiave_id` INT UNSIGNED NOT NULL,
  INDEX `fk_regia_has_parola_chiave_parola_chiave1_idx` (`parola_chiave_id` ASC) VISIBLE,
  INDEX `fk_regia_has_parola_chiave_regia1_idx` (`regia_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_regia_has_parola_chiave_regia1`
    FOREIGN KEY (`regia_id`)
    REFERENCES `disneydb`.`regia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regia_has_parola_chiave_parola_chiave1`
    FOREIGN KEY (`parola_chiave_id`)
    REFERENCES `disneydb`.`parola_chiave` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`media` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`media` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `immagini` MEDIUMBLOB NULL,
  `video` LONGBLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`media_personaggio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`media_personaggio` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`media_personaggio` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `media_id` INT UNSIGNED NOT NULL,
  `personaggio_id` INT UNSIGNED NOT NULL,
  INDEX `fk_media_has_personaggio_personaggio1_idx` (`personaggio_id` ASC) VISIBLE,
  INDEX `fk_media_has_personaggio_media1_idx` (`media_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_media_has_personaggio_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `disneydb`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_has_personaggio_personaggio1`
    FOREIGN KEY (`personaggio_id`)
    REFERENCES `disneydb`.`personaggio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`media_regia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`media_regia` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`media_regia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `media_id` INT UNSIGNED NOT NULL,
  `regia_id` INT UNSIGNED NOT NULL,
  INDEX `fk_media_has_regia_regia1_idx` (`regia_id` ASC) VISIBLE,
  INDEX `fk_media_has_regia_media1_idx` (`media_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_media_has_regia_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `disneydb`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_has_regia_regia1`
    FOREIGN KEY (`regia_id`)
    REFERENCES `disneydb`.`regia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`personaggio_attore_correlato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`personaggio_attore_correlato` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`personaggio_attore_correlato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `personaggio_id` INT UNSIGNED NOT NULL,
  `regia_id` INT UNSIGNED NOT NULL,
  INDEX `fk_personaggio_has_regia_regia1_idx` (`regia_id` ASC) VISIBLE,
  INDEX `fk_personaggio_has_regia_personaggio1_idx` (`personaggio_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_personaggio_has_regia_personaggio1`
    FOREIGN KEY (`personaggio_id`)
    REFERENCES `disneydb`.`personaggio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personaggio_has_regia_regia1`
    FOREIGN KEY (`regia_id`)
    REFERENCES `disneydb`.`regia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`personaggio_correlato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`personaggio_correlato` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`personaggio_correlato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `personaggio_id` INT UNSIGNED NOT NULL,
  `personaggio_correlato_id` INT UNSIGNED NOT NULL,
  INDEX `fk_personaggio_has_personaggio_personaggio2_idx` (`personaggio_correlato_id` ASC) VISIBLE,
  INDEX `fk_personaggio_has_personaggio_personaggio1_idx` (`personaggio_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_personaggio_has_personaggio_personaggio1`
    FOREIGN KEY (`personaggio_id`)
    REFERENCES `disneydb`.`personaggio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personaggio_has_personaggio_personaggio2`
    FOREIGN KEY (`personaggio_correlato_id`)
    REFERENCES `disneydb`.`personaggio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`regia_correlato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`regia_correlato` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`regia_correlato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `regia_id` INT UNSIGNED NOT NULL,
  `regia_correlato_id` INT UNSIGNED NOT NULL,
  INDEX `fk_regia_has_regia_regia2_idx` (`regia_correlato_id` ASC) VISIBLE,
  INDEX `fk_regia_has_regia_regia1_idx` (`regia_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_regia_has_regia_regia1`
    FOREIGN KEY (`regia_id`)
    REFERENCES `disneydb`.`regia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regia_has_regia_regia2`
    FOREIGN KEY (`regia_correlato_id`)
    REFERENCES `disneydb`.`regia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`articolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`articolo` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`articolo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titolo` VARCHAR(50) NOT NULL,
  `data_uscita` DATE NOT NULL,
  `durata` VARCHAR(7) NOT NULL,
  `trama` MEDIUMTEXT NOT NULL,
  `votazione` DECIMAL(2,1) NULL,
  `prezzo` DOUBLE(4,2) NOT NULL,
  `locandina` MEDIUMBLOB NOT NULL,
  `trailer` LONGBLOB NOT NULL,
  `categoria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`articolo preferito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`articolo preferito` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`articolo preferito` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `articolo_id` INT UNSIGNED NOT NULL,
  `utente_id` INT UNSIGNED NOT NULL,
  INDEX `fk_articolo_has_utente_utente1_idx` (`utente_id` ASC) VISIBLE,
  INDEX `fk_articolo_has_utente_articolo1_idx` (`articolo_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articolo_has_utente_articolo1`
    FOREIGN KEY (`articolo_id`)
    REFERENCES `disneydb`.`articolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articolo_has_utente_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `disneydb`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`articolo_correlato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`articolo_correlato` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`articolo_correlato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `articolo_id` INT UNSIGNED NOT NULL,
  `articolo_correlato_id` INT UNSIGNED NOT NULL,
  INDEX `fk_articolo_has_articolo_articolo2_idx` (`articolo_correlato_id` ASC) VISIBLE,
  INDEX `fk_articolo_has_articolo_articolo1_idx` (`articolo_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articolo_has_articolo_articolo1`
    FOREIGN KEY (`articolo_id`)
    REFERENCES `disneydb`.`articolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articolo_has_articolo_articolo2`
    FOREIGN KEY (`articolo_correlato_id`)
    REFERENCES `disneydb`.`articolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`articolo_parola_chiave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`articolo_parola_chiave` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`articolo_parola_chiave` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `articolo_id` INT UNSIGNED NOT NULL,
  `parola_chiave_id` INT UNSIGNED NOT NULL,
  INDEX `fk_articolo_has_parola_chiave_parola_chiave1_idx` (`parola_chiave_id` ASC) VISIBLE,
  INDEX `fk_articolo_has_parola_chiave_articolo1_idx` (`articolo_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articolo_has_parola_chiave_articolo1`
    FOREIGN KEY (`articolo_id`)
    REFERENCES `disneydb`.`articolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articolo_has_parola_chiave_parola_chiave1`
    FOREIGN KEY (`parola_chiave_id`)
    REFERENCES `disneydb`.`parola_chiave` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`articolo_ordinato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`articolo_ordinato` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`articolo_ordinato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `articolo_id` INT UNSIGNED NOT NULL,
  `ordine_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articolo_has_ordine_ordine1_idx` (`ordine_id` ASC) VISIBLE,
  INDEX `fk_articolo_has_ordine_articolo1_idx` (`articolo_id` ASC) VISIBLE,
  CONSTRAINT `fk_articolo_has_ordine_articolo1`
    FOREIGN KEY (`articolo_id`)
    REFERENCES `disneydb`.`articolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articolo_has_ordine_ordine1`
    FOREIGN KEY (`ordine_id`)
    REFERENCES `disneydb`.`ordine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`backstage_articolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`backstage_articolo` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`backstage_articolo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `regia_id` INT UNSIGNED NOT NULL,
  `articolo_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_regia_has_articolo_articolo1_idx` (`articolo_id` ASC) VISIBLE,
  INDEX `fk_regia_has_articolo_regia1_idx` (`regia_id` ASC) VISIBLE,
  CONSTRAINT `fk_regia_has_articolo_regia1`
    FOREIGN KEY (`regia_id`)
    REFERENCES `disneydb`.`regia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regia_has_articolo_articolo1`
    FOREIGN KEY (`articolo_id`)
    REFERENCES `disneydb`.`articolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`media_articolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`media_articolo` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`media_articolo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `articolo_id` INT UNSIGNED NOT NULL,
  `media_id` INT UNSIGNED NOT NULL,
  INDEX `fk_articolo_has_media_media1_idx` (`media_id` ASC) VISIBLE,
  INDEX `fk_articolo_has_media_articolo1_idx` (`articolo_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articolo_has_media_articolo1`
    FOREIGN KEY (`articolo_id`)
    REFERENCES `disneydb`.`articolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articolo_has_media_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `disneydb`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disneydb`.`personaggio_articolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disneydb`.`personaggio_articolo` ;

CREATE TABLE IF NOT EXISTS `disneydb`.`personaggio_articolo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `articolo_id` INT UNSIGNED NOT NULL,
  `personaggio_id` INT UNSIGNED NOT NULL,
  INDEX `fk_articolo_has_personaggio_personaggio1_idx` (`personaggio_id` ASC) VISIBLE,
  INDEX `fk_articolo_has_personaggio_articolo1_idx` (`articolo_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articolo_has_personaggio_articolo1`
    FOREIGN KEY (`articolo_id`)
    REFERENCES `disneydb`.`articolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articolo_has_personaggio_personaggio1`
    FOREIGN KEY (`personaggio_id`)
    REFERENCES `disneydb`.`personaggio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
